server:
  port: 0

spring:
  application:
    name: animal-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
      port: 271017
  graphql:
    graphiql:
      enabled: true

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

