server:
  port: 0

spring:
  application:
    name: animal-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
      port: 27017
  graphql:
    graphiql:
      enabled: true

axon:
  axonserver:
    servers: ${AXON_SERVER}
  serializer:
    general: jackson
    events: jackson
    messages: jackson

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}

