server:
  port: 0

application:
  count:
    max: 5

web-client:
  base-url: http://localhost:9000/payment-service

spring:
  application:
    name: application-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
      port: 271017

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
