server:
  port: 0

application:
  count:
    max: 5

web-client:
  base-url: ${GATEWAY_SERVICE_URL}/payment-service

spring:
  application:
    name: application-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
      port: 271017

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}

axon:
  axonserver:
    servers: ${AXON_SERVER}
  serializer:
    general: jackson
    events: jackson
    messages: jackson
