server:
  port: 0

application:
  count:
    max: 5

web-client:
  base-url: http://localhost:9000/payment-service

spring:
  application:
    name: application-service
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.gf4mguw.mongodb.net/?retryWrites=true&w=majority
      database: cluster0
      port: 271017

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
