spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  instance:
    name: ${DISCOVERY_HOSTNAME}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}
