spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      routes:
        - id: animal-service
          uri: lb://animal-service/graphql
          predicates:
            - Path=/animal-service/graphql/**

        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/application-service/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**

server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
