spring:
  application:
    name: payment-service
  r2dbc:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yaml
    url: ${LIQUIBASE_MYSQL_URL}
    user: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

axon:
  axonserver:
    servers: ${AXON_SERVER}
  serializer:
    general: jackson
    events: jackson
    messages: jackson

server:
  port: 0

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  application-fee: 60

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}

