spring:
  application:
    name: payment-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/payment_store
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yaml
    url: jdbc:mysql://localhost:3306/payment_store
    user: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson

server:
  port: 0

stripe:
  secret-key: sk_test_4eC39HqLyjWDarjtT1zdp7dc
  application-fee: 60

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

