server:
  port: 0

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson

spring:
  security:
    token:
      life-time: 86400000
      secret-key: MgtqlZi01l05/3fpeck2ZFwtjeqxrndplJK0acQ4l/pPj+pY5yo+DAGx/24ejx/8Icj+mJXtsCl+xfWVwezzAjmchy5A8VlQmBFmFr3uelw=
  application:
    name: user-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
      port: 271017

resilience4j:
  circuitbreaker:
    circuitbreaker-aspect-order: 1
    instances:
      payment-service:
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 4
        waitDurationInOpenState: 25s
      animal-service:
        failureRateThreshold: 60
        permittedNumberOfCallsInHalfOpenState: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 25s
  retry:
    retry-aspect-order: 2
    instances:
      payment-service:
        max-retry-Attempts: 5
        wait-duration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        register-health-indicator: true
      animal-service:
        max-retry-Attempts: 3
        wait-duration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        register-health-indicator: true

payment:
  validation:
    base-url: http://localhost:9000/payment-service

gemini:
  base-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
  api:
    key: ${GEMINI_API_KEY}

animal:
  profile:
    base-url: http://localhost:9000/animal-service/graphql

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

